
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, open the command palette and run the command "Firebase: Switch Project".
// Or right-click on `firebase.json` in the file explorer and select "Firebase: Switch Project".
export const firebaseConfig = {
  "apiKey": "your-api-key",
  "authDomain": "your-project-id.firebaseapp.com",
  "projectId": "your-project-id",
  "storageBucket": "your-project-id.appspot.com",
  "messagingSenderId": "your-sender-id",
  "appId": "your-app-id"
};
